/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'text' : string,
  'messageType' : { 'user' : null } |
    { 'jigyansa' : null },
  'timestamp' : Time,
}
export interface Conversation {
  'messages' : Array<ChatMessage>,
  'timestamp' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'backfillExistingUsers' : ActorMethod<
    [Array<[Principal, string]>],
    undefined
  >,
  'clearConversationHistory' : ActorMethod<[null], undefined>,
  'getAllUserMessagesQuery' : ActorMethod<[Principal], Array<ChatMessage>>,
  'getConversationHistory' : ActorMethod<[null], Array<Conversation>>,
  'getMessageExamples' : ActorMethod<[null], Array<[string, string]>>,
  'getUserName' : ActorMethod<[null], [] | [string]>,
  'isFirstTimeUser' : ActorMethod<[null], boolean>,
  'isNameSet' : ActorMethod<[null], boolean>,
  'onboardingComplete' : ActorMethod<[null], undefined>,
  'rollbackPromptHistory' : ActorMethod<[null], undefined>,
  'sendMessage' : ActorMethod<[string], ChatMessage>,
  'setUserName' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];