/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'text' : IDL.Text,
  'messageType' : IDL.Variant({ 'user' : IDL.Null, 'jigyansa' : IDL.Null }),
  'timestamp' : Time,
});
export const Conversation = IDL.Record({
  'messages' : IDL.Vec(ChatMessage),
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'backfillExistingUsers' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      [],
      [],
    ),
  'clearConversationHistory' : IDL.Func([IDL.Null], [], []),
  'getAllUserMessagesQuery' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChatMessage)],
      [],
    ),
  'getConversationHistory' : IDL.Func([IDL.Null], [IDL.Vec(Conversation)], []),
  'getMessageExamples' : IDL.Func(
      [IDL.Null],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getUserName' : IDL.Func([IDL.Null], [IDL.Opt(IDL.Text)], []),
  'isFirstTimeUser' : IDL.Func([IDL.Null], [IDL.Bool], []),
  'isNameSet' : IDL.Func([IDL.Null], [IDL.Bool], []),
  'onboardingComplete' : IDL.Func([IDL.Null], [], []),
  'rollbackPromptHistory' : IDL.Func([IDL.Null], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
  'setUserName' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'text' : IDL.Text,
    'messageType' : IDL.Variant({ 'user' : IDL.Null, 'jigyansa' : IDL.Null }),
    'timestamp' : Time,
  });
  const Conversation = IDL.Record({
    'messages' : IDL.Vec(ChatMessage),
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'backfillExistingUsers' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        [],
        [],
      ),
    'clearConversationHistory' : IDL.Func([IDL.Null], [], []),
    'getAllUserMessagesQuery' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChatMessage)],
        [],
      ),
    'getConversationHistory' : IDL.Func(
        [IDL.Null],
        [IDL.Vec(Conversation)],
        [],
      ),
    'getMessageExamples' : IDL.Func(
        [IDL.Null],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getUserName' : IDL.Func([IDL.Null], [IDL.Opt(IDL.Text)], []),
    'isFirstTimeUser' : IDL.Func([IDL.Null], [IDL.Bool], []),
    'isNameSet' : IDL.Func([IDL.Null], [IDL.Bool], []),
    'onboardingComplete' : IDL.Func([IDL.Null], [], []),
    'rollbackPromptHistory' : IDL.Func([IDL.Null], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [ChatMessage], []),
    'setUserName' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };