/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChatMessage {
    text: string;
    messageType: Variant_user_jigyansa;
    timestamp: Time;
}
export type Time = bigint;
export interface Conversation {
    messages: Array<ChatMessage>;
    timestamp: Time;
}
export enum Variant_user_jigyansa {
    user = "user",
    jigyansa = "jigyansa"
}
export interface backendInterface {
    backfillExistingUsers(users: Array<[Principal, string]>): Promise<void>;
    clearConversationHistory(arg0: null): Promise<void>;
    getAllUserMessagesQuery(id: Principal): Promise<Array<ChatMessage>>;
    getConversationHistory(arg0: null): Promise<Array<Conversation>>;
    getMessageExamples(arg0: null): Promise<Array<[string, string]>>;
    getUserName(arg0: null): Promise<string | null>;
    isFirstTimeUser(arg0: null): Promise<boolean>;
    isNameSet(arg0: null): Promise<boolean>;
    onboardingComplete(arg0: null): Promise<void>;
    rollbackPromptHistory(arg0: null): Promise<void>;
    sendMessage(message: string): Promise<ChatMessage>;
    setUserName(name: string): Promise<void>;
}
import type { ChatMessage as _ChatMessage, Conversation as _Conversation, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async backfillExistingUsers(arg0: Array<[Principal, string]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.backfillExistingUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backfillExistingUsers(arg0);
            return result;
        }
    }
    async clearConversationHistory(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearConversationHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearConversationHistory(arg0);
            return result;
        }
    }
    async getAllUserMessagesQuery(arg0: Principal): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserMessagesQuery(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserMessagesQuery(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversationHistory(arg0: null): Promise<Array<Conversation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversationHistory(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversationHistory(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageExamples(arg0: null): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageExamples(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageExamples(arg0);
            return result;
        }
    }
    async getUserName(arg0: null): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserName(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserName(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isFirstTimeUser(arg0: null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFirstTimeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFirstTimeUser(arg0);
            return result;
        }
    }
    async isNameSet(arg0: null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isNameSet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isNameSet(arg0);
            return result;
        }
    }
    async onboardingComplete(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.onboardingComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.onboardingComplete(arg0);
            return result;
        }
    }
    async rollbackPromptHistory(arg0: null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rollbackPromptHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rollbackPromptHistory(arg0);
            return result;
        }
    }
    async sendMessage(arg0: string): Promise<ChatMessage> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return from_candid_ChatMessage_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return from_candid_ChatMessage_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserName(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserName(arg0);
            return result;
        }
    }
}
function from_candid_ChatMessage_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Conversation_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conversation): Conversation {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    messageType: {
        user: null;
    } | {
        jigyansa: null;
    };
    timestamp: _Time;
}): {
    text: string;
    messageType: Variant_user_jigyansa;
    timestamp: Time;
} {
    return {
        text: value.text,
        messageType: from_candid_variant_n4(_uploadFile, _downloadFile, value.messageType),
        timestamp: value.timestamp
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    messages: Array<_ChatMessage>;
    timestamp: _Time;
}): {
    messages: Array<ChatMessage>;
    timestamp: Time;
} {
    return {
        messages: from_candid_vec_n1(_uploadFile, _downloadFile, value.messages),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    jigyansa: null;
}): Variant_user_jigyansa {
    return "user" in value ? Variant_user_jigyansa.user : "jigyansa" in value ? Variant_user_jigyansa.jigyansa : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Conversation>): Array<Conversation> {
    return value.map((x)=>from_candid_Conversation_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
